[package]
name = "laminate_analysis"
version = "0.1.0"
authors = ["BORLOT Jean-Michel <jmborlot@free.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

#[lib]
#crate-type = ["cdylib"]

